name: Test Workflow
on: [push]
jobs:
  test:
    runs: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
      - uses: actions/checkout@v4
      - name: Another step
        uses: actions/checkout@v3
